import imgProfile from "../img/profile.ico";

export const nightTheme = {
  "--color-back": "black",
  "--white-black": "#e9e8e6",
  "--contrast-text": "#ffffff",
  "--back-menu": "#0f9393b3",
  "--color-menuG": "#1db3b3",
  "--wrap-opacity": "0",
  "--background-wrap": "#1d1b1b",
  "--background-header": "#252c2f",
  "--background-first": "#1d2225",
  "--background-second": "#252c2f",
  "--background-third": "#053c29",
  "--color-bg-wrap": "#86909b",
  "--background-nav": "#011e16",
  "--color-nav": "#0f9393b3",
  "--color-text": "#b5a68a",
  "--background-wrap-rgb": "rgb(29, 27, 27, 0)",
  "--color-checked": "#0f9393b3",
  "--background-note": "#1f4f5c",
  "--color-rate": "#1db3b3",
  "--border-note": "#0f9393b3",
  "--background-intense": "grey",
  "--color-intense": "#1db3b3",
  "--background-even": "#1e282e",
  "--color-about": "#128867",
  "--background-parts-answ": "#0f9393b3",
  "--color-fill": "#0e4949",
  "--border-fill": "#DADEE8",
};

export const dayTheme = {
  "--color-back": "#e9e8e6",
  "--white-black": "#5f6368",
  "--back-menu": "#2a313e",
  "--color-menuG": "#5f6368",
  "--contrast-text": "black",
  "--background-wrap": "#ffffff",
  "--background-header": "#f7f6f6",
  "--background-first": "#fcfbf7",
  "--background-second": "#ededed",
  "--background-third": "#337AB7",
  "--color-bg-wrap": "#5f6368",
  "--background-nav": "#5c8ece",
  "--color-nav": "#5c8ece",
  "--color-text": "black",
  "--background-wrap-rgb": "rgb(252, 252, 252)",
  "--color-checked": "#ed666d",
  "--background-note": "#5c8ece",
  "--color-rate": "#64b5f6",
  "--border-note": "#64b5f6",
  "--background-intense": "#0A58CA",
  "--color-intense": "#597db4",
  "--background-even": "#F7F6F6",
  "--color-about": "#5d8fd0",
  "--background-parts-answ": "blanchedalmond",
  "--color-fill": "#EDEFF4",
  "--border-fill": "#DADEE8",
};
export const defaultColorBack = "white";
export const defaultStyleValue = {
  colorBack: dayTheme["--color-back"],
  colorBackN: nightTheme["--color-back"],
  wrapOpacity: 100,
};
export const defaultSettings = { colorBack: defaultColorBack };
export const defaultAvatar = imgProfile;
export const DEFAUL_USER_DATA = {
  name: "",
  email: "",
  img: defaultAvatar,
  password: "",
  settings: defaultSettings,
};
