const dataBase = {
  users: [
    {
      id: 1,
      name: "test user",
      email: "test@test.test",
      password: 1,
      sessions: [],
      imgu: "https://firebasestorage.googleapis.com/v0/b/words-d2019.appspot.com/o/avatars%2Fav1.png?alt=media&token=d83bc75a-2744-49c2-b961-93c631c4351f",
    },
  ],
  user: {
    id: "",
    name: "",
  },

  expressionsList: [
    {
      id: 1,
      stage: 7,
      expression: "Der Rock",
      phrase: "Ihr Rock ist total altmodisch.",
      nextDate: new Date(),
      history: [
        { action: "add", date: new Date("2022-04-20") },
        { action: "read by the plan", date: new Date("2022-04-20") },
        { action: "read by the plan", date: new Date("2022-04-21") },
        { action: "read by the plan", date: new Date("2022-04-22") },
        { action: "read by the plan", date: new Date("2022-04-23") },
        { action: "read by the plan", date: new Date("2022-04-24") },
        { action: "read by the plan", date: new Date("2022-04-25") },
        { action: "read by the plan", date: new Date("2022-04-26") },
      ],
    },
    {
      id: 2,
      stage: 1,
      expression: "die Mütze",
      phrase: "Das ist deine neue Mütze, Schatz.",
      nextDate: new Date("2022-05-01"),
      history: [
        { action: "add", date: new Date("2022-04-30") },
        { action: "read by the plan", date: new Date("2022-04-30") },
      ],
    },
    {
      id: 3,
      stage: 0,
      expression: "Das Hemd",
      phrase: "Mir gefällt dieses Hemd",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 4,
      stage: 0,
      expression: "Der Badeanzug",
      phrase: "Wo finde ich einen Badeanzug?",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 44,
      stage: 0,
      expression: "Der Anzug",
      phrase: "Ich brauche einen Anzug.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 45,
      stage: 0,
      expression: "Das Kleid",
      phrase: "das Kleid ist rot.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 5,
      stage: 0,
      expression: "I think",
      phrase: "I think he is taller than you, but I can’t be certain.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 6,
      stage: 0,
      expression: "I guess",
      phrase: "I guess she prefers roses.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 7,
      stage: 0,
      expression: "Not sure",
      phrase: "I’m not sure we should eat this meal.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 8,
      stage: 0,
      expression: "Not quite sure",
      phrase:
        "Anna explained the task but I’m not quite sure they understood her.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 81,
      stage: 0,
      expression: "Probably",
      phrase: "This is probably the rarest mineral in the world.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 82,
      stage: 0,
      expression: "I’m positive",
      phrase: "I’m positive I left my wallet in my car.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 83,
      stage: 0,
      expression: "I’m certain",
      phrase: "I’m certain we made the right decision.",
      nextDate: new Date(),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 9,
      stage: 0,
      expression: "Would you like",
      phrase: "Would you like a cup of tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 91,
      stage: 0,
      expression: "Do you want",
      phrase: "Do you want tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 92,
      stage: 0,
      expression: "How about",
      phrase: "How about a cup of tea?",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 93,
      stage: 0,
      expression: "You shoud",
      phrase: "You shoud sleep better.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 94,
      stage: 0,
      expression: "Why don’t you",
      phrase: "Why don’t you come to our party tomorrow? ",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 95,
      stage: 0,
      expression: "If I were you",
      phrase: "If I were you, I would wait for a lawyer.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 96,
      stage: 0,
      expression: "You’d better",
      phrase: "You’d better take an umbrella.",
      nextDate: new Date("2022-09-30"),
      history: [{ action: "add", date: new Date("2022-09-30") }],
    },
    {
      id: 10,
      stage: 0,
      expression: "Bać się",
      phrase: "Boję się podejmowania decyzji",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 61,
      stage: 0,
      expression: "Zmęczyć się",
      phrase: "Myślę, że nie zmęczy się tą podróżą.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 62,
      stage: 0,
      expression: "Śmiać się",
      phrase: "Zawsze się śmiejemy z twoich sucharów.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 63,
      stage: 0,
      expression: "Czuć się",
      phrase: "Czuję się dzisiaj okropnie.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 64,
      stage: 0,
      expression: "Uczyć się",
      phrase: "Ja uczę was polskiego, a wy uczycie się języka polskiego.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
    {
      id: 65,
      stage: 0,
      expression: "Szykować się",
      phrase: "Ela szykuje się na randkę.",
      nextDate: new Date("2022-04-25"),
      history: [{ action: "add", date: new Date() }],
    },
  ],
  collectionsList: [
    {
      id: 1,
      name: "Die Kleidung",
      note: "Deutsch",
    },
    {
      id: 2,
      name: "SIĘ",
      note: "Polska",
    },
  ],

  extraList: [
    {
      id: 1,
      collectionid: 1,
      question: "Der Rock",
      answer: "Спідниця",
      note: "Ihr Rock ist total altmodisch.",
    },
    {
      id: 2,
      collectionid: 1,
      question: "die Mütze",
      answer: "Шапка",
      note: "Das ist deine neue Mütze, Schatz.",
    },
    {
      id: 3,
      collectionid: 1,
      question: "Das Hemd",
      answer: "Сорочка",
      note: "Mir gefällt dieses Hemd",
    },
    {
      id: 4,
      collectionid: 1,
      question: "Der Badeanzug",
      answer: "Купальник",
      note: "Wo finde ich einen Badeanzug?",
    },
    {
      id: 5,
      collectionid: 1,
      question: "Der Anzug",
      answer: "Костюм",
      note: "Ich brauche einen Anzug.",
    },
    {
      id: 6,
      collectionid: 1,
      question: "Das Kleid",
      answer: "Сукня",
      note: "das Kleid ist rot.",
    },
    {
      id: 7,
      collectionid: 2,
      question: "Bać się",
      answer: "Боятися",
      note: "Boję się podejmowania decyzji",
    },
    {
      id: 8,
      collectionid: 2,
      question: "Zmęczyć się",
      answer: "Втомитися",
      note: "Myślę, że nie zmęczy się tą podróżą.",
    },
    {
      id: 9,
      collectionid: 2,
      question: "Śmiać się",
      answer: "Сміятися",
      note: "Zawsze się śmiejemy z twoich sucharów.",
    },
    {
      id: 10,
      collectionid: 2,
      question: "Czuć się",
      answer: "Відчувати себе",
      note: "Czuję się dzisiaj okropnie.",
    },
    {
      id: 11,
      collectionid: 2,
      question: "Uczyć się",
      answer: "Навчатися",
      note: "Ja uczę was polskiego, a wy uczycie się języka polskiego.",
    },
    {
      id: 12,
      collectionid: 2,
      question: "Szykować się",
      answer: "Готуватися",
      note: "Ela szykuje się na randkę.",
    },
  ],

  publicCollections: [
    {
      id: "p3",
      name: "Wojny w XVII wieku (Historia)",
      note: "Historia",
      user: "admin",
    },
    {
      id: "p1",
      name: "Present continuous S",
      note: "English",
      user: "admin",
    },
    {
      id: "p2",
      name: "Present continuous Q",
      note: "English",
      user: "admin",
    },

    {
      id: "p4",
      name: "Present continuous Qb",
      note: "English",
      user: "admin",
    },
    {
      id: "p5",
      name: "Present simple S",
      note: "English",
      user: "admin",
    },
    {
      id: "p6",
      name: "Present simple Q",
      note: "English",
      user: "admin",
    },
    {
      id: "p7",
      name: "Present simple Qb",
      note: "English",
      user: "admin",
    },
    { id: "p8", name: "To be Q", note: "", user: "admin" },
    { id: "p9", name: "To be S", note: "", user: "admin" },
  ],
  publicContent: [
    {
      id: "p3_0",
      collectionid: "p3",
      question: "Wyjaśnij określenie monarcha elekcyjny",
      answer:
        "forma rządów, w której cała władza spoczywa w rękach monarchy, który jest źródłem prawa i stoi ponad nim",
      note: "",
    },
    {
      id: "p3_1",
      collectionid: "p3",
      question: " W którym wieku na tron polski zostali wybrani Wazowie?",
      answer: "XVi",
      note: "Panowanie Wazów rozpoczęło się w Polsce w 1587 roku, gdy wybrany został królem Zygmunt III Waza a zakończyło wraz z abdykacją Jana Kazimierza w 1668 roku",
    },
    {
      id: "p3_2",
      collectionid: "p3",
      question: "Co to jest wolna elekcja",
      answer: "wybór władcy bez względu na pochodzenie dynastyczne",
      note: "",
    },
    {
      id: "p3_3",
      collectionid: "p3",
      question:
        " Kto był pierwszym królem z dynastii Wazów na tronie Rzeczypospolitej?",
      answer: "Zygmunt iii Waza został wybrany w 1587 na króla Polski",
      note: "",
    },
    {
      id: "p3_4",
      collectionid: "p3",
      question: "Kto był matka Zygmunta III Wazy",
      answer: "Katarzyna Jagiellonka, najmłodsza córka Zygmunta Starego",
      note: "",
    },
    {
      id: "p3_5",
      collectionid: "p3",
      question: "Wielka smuta to",
      answer:
        "okres w historii Rosji od śmierci ostatniego cara z dynastii Rurykowiczów w 1598 r. do objęcia tronu przez dynastię Romanowów w 1613 r.; charakteryzujący się walkami o tron, intrygami uzurpatorów, interwencjami wojsk polskich i szwedzkich oraz powstaniami chłopskimi, które prowadziły do głębokiego kryzysu społeczno-gospodarczego i klęsk głodu",
      note: "",
    },
    {
      id: "p3_6",
      collectionid: "p3",
      question: "Samodzierżawie to",
      answer:
        "termin określający rządy carów rosyjskich, stosowany w Rosji od drugiej połowy XV w. równolegle z tytułem cara",
      note: "",
    },
    {
      id: "p1_0",
      collectionid: "p1",
      question: "Я сейчас покупаю",
      answer: "I'm buying",
      note: "",
    },
    {
      id: "p1_1",
      collectionid: "p1",
      question: "Ты сейчас покупаешь",
      answer: "you're buying",
      note: "",
    },
    {
      id: " p1_2",
      collectionid: "p1",
      question: "Она сейчас покупает",
      answer: "She's buying",
      note: "",
    },
    {
      id: " p1_3",
      collectionid: "p1",
      question: "Он сейчас покупает",
      answer: "He's buying",
      note: "",
    },
    {
      id: " p1_4",
      collectionid: "p1",
      question: "Мы сейчас покупаем",
      answer: "We're buying",
      note: "",
    },
    {
      id: " p1_5",
      collectionid: "p1",
      question: "Вы сейчас покупаете",
      answer: "You're buying",
      note: "",
    },
    {
      id: " p1_6",
      collectionid: "p1",
      question: "Они сейчас покупают",
      answer: "They're buying",
      note: "",
    },
    {
      id: " p1_7",
      collectionid: "p1",
      question: "Я сейчас борюсь",
      answer: "I'm fighting",
      note: "",
    },
    {
      id: " p1_8",
      collectionid: "p1",
      question: "Ты сейчас борешься",
      answer: "you're fighting",
      note: "",
    },
    {
      id: " p1_9",
      collectionid: "p1",
      question: "Она сейчас борется",
      answer: "She's fighting",
      note: "",
    },
    {
      id: " p1_10",
      collectionid: "p1",
      question: "Он сейчас борется",
      answer: "He's fighting",
      note: "",
    },
    {
      id: " p1_11",
      collectionid: "p1",
      question: "Мы сейчас боремся",
      answer: "We're fighting",
      note: "",
    },
    {
      id: " p1_12",
      collectionid: "p1",
      question: "Вы сейчас боретесь",
      answer: "You're fighting",
      note: "",
    },
    {
      id: " p1_13",
      collectionid: "p1",
      question: "Они сейчас борются",
      answer: "They're fighting",
      note: "",
    },
    {
      id: " p1_14",
      collectionid: "p1",
      question: "Я сейчас пишу",
      answer: "I'm writing",
      note: "",
    },
    {
      id: " p1_15",
      collectionid: "p1",
      question: "Ты сейчас пишешь",
      answer: "you're writing",
      note: "",
    },
    {
      id: " p1_16",
      collectionid: "p1",
      question: "Она сейчас пишет",
      answer: "She's writing",
      note: "",
    },
    {
      id: " p1_17",
      collectionid: "p1",
      question: "Он сейчас пишет",
      answer: "He's writing",
      note: "",
    },
    {
      id: " p1_18",
      collectionid: "p1",
      question: "Мы сейчас пишем",
      answer: "We're writing",
      note: "",
    },
    {
      id: " p1_19",
      collectionid: "p1",
      question: "Вы сейчас пишете",
      answer: "You're writing",
      note: "",
    },
    {
      id: " p1_20",
      collectionid: "p1",
      question: "Они сейчас пишут",
      answer: "They're writing",
      note: "",
    },
    {
      id: " p1_21",
      collectionid: "p1",
      question: "Я сейчас читаю",
      answer: "I'm reading",
      note: "",
    },
    {
      id: " p1_22",
      collectionid: "p1",
      question: "Ты сейчас читаешь",
      answer: "you're reading",
      note: "",
    },
    {
      id: " p1_23",
      collectionid: "p1",
      question: "Она сейчас читает",
      answer: "She's reading",
      note: "",
    },
    {
      id: " p1_24",
      collectionid: "p1",
      question: "Он сейчас читает",
      answer: "He's reading",
      note: "",
    },
    {
      id: " p1_25",
      collectionid: "p1",
      question: "Мы сейчас читаем",
      answer: "We're reading",
      note: "",
    },
    {
      id: " p1_26",
      collectionid: "p1",
      question: "Вы сейчас читаете",
      answer: "You're reading",
      note: "",
    },
    {
      id: " p1_27",
      collectionid: "p1",
      question: "Они сейчас читают",
      answer: "They're reading",
      note: "",
    },
    {
      id: " p1_28",
      collectionid: "p1",
      question: "Я сейчас выбираю",
      answer: "I'm choosing",
      note: "",
    },
    {
      id: " p1_29",
      collectionid: "p1",
      question: "Ты сейчас выбираешь",
      answer: "you're choosing",
      note: "",
    },
    {
      id: " p1_30",
      collectionid: "p1",
      question: "Она сейчас выбирает",
      answer: "She's choosing",
      note: "",
    },
    {
      id: " p1_31",
      collectionid: "p1",
      question: "Он сейчас выбирает",
      answer: "He's choosing",
      note: "",
    },
    {
      id: " p1_32",
      collectionid: "p1",
      question: "Мы сейчас выбираем",
      answer: "We're choosing",
      note: "",
    },
    {
      id: " p1_33",
      collectionid: "p1",
      question: "Вы сейчас выбираете",
      answer: "You're choosing",
      note: "",
    },
    {
      id: " p1_34",
      collectionid: "p1",
      question: "Они сейчас выбирают",
      answer: "They're choosing",
      note: "",
    },
    {
      id: " p1_35",
      collectionid: "p1",
      question: "Я сейчас прячусь",
      answer: "I'm hiding",
      note: "",
    },
    {
      id: " p1_36",
      collectionid: "p1",
      question: "Ты сейчас прячешься",
      answer: "you're hiding",
      note: "",
    },
    {
      id: " p1_37",
      collectionid: "p1",
      question: "Она сейчас прячется",
      answer: "She's hiding",
      note: "",
    },
    {
      id: " p1_38",
      collectionid: "p1",
      question: "Он сейчас прячется",
      answer: "He's hiding",
      note: "",
    },
    {
      id: " p1_39",
      collectionid: "p1",
      question: "Оно сейчас прячется",
      answer: "It's hiding",
      note: "",
    },
    {
      id: " p1_40",
      collectionid: "p1",
      question: "Мы сейчас прячемся",
      answer: "We're hiding",
      note: "",
    },
    {
      id: " p1_41",
      collectionid: "p1",
      question: "Вы сейчас прячетесь",
      answer: "you're hiding",
      note: "",
    },
    {
      id: " p1_42",
      collectionid: "p1",
      question: "Они сейчас прячутся",
      answer: "They're hiding",
      note: "",
    },
    {
      id: " p1_43",
      collectionid: "p1",
      question: "Я сейчас строю",
      answer: "I'm building",
      note: "",
    },
    {
      id: " p1_44",
      collectionid: "p1",
      question: "Ты сейчас строишь",
      answer: "You're building",
      note: "",
    },
    {
      id: " p1_45",
      collectionid: "p1",
      question: "Она сейчас строит",
      answer: "She's building",
      note: "",
    },
    {
      id: " p1_46",
      collectionid: "p1",
      question: "Он сейчас строит",
      answer: "He's building",
      note: "",
    },
    {
      id: " p1_47",
      collectionid: "p1",
      question: "Мы сейчас строим",
      answer: "We're building",
      note: "",
    },
    {
      id: " p1_48",
      collectionid: "p1",
      question: "Вы сейчас строите",
      answer: "You're building",
      note: "",
    },
    {
      id: " p1_49",
      collectionid: "p1",
      question: "Они сейчас строят",
      answer: "They're building",
      note: "",
    },
    {
      id: " p1_50",
      collectionid: "p1",
      question: "Я сейчас сплю",
      answer: "I'm slipping",
      note: "",
    },
    {
      id: " p1_51",
      collectionid: "p1",
      question: "Ты сейчас спишь",
      answer: "you're slipping",
      note: "",
    },
    {
      id: " p1_52",
      collectionid: "p1",
      question: "Она сейчас спит",
      answer: "She's slipping",
      note: "",
    },
    {
      id: " p1_53",
      collectionid: "p1",
      question: "Он сейчас спит",
      answer: "He's slipping",
      note: "",
    },
    {
      id: " p1_54",
      collectionid: "p1",
      question: "Мы сейчас спим",
      answer: "We're slipping",
      note: "",
    },
    {
      id: " p1_55",
      collectionid: "p1",
      question: "Вы сейчас спите",
      answer: "You're slipping",
      note: "",
    },
    {
      id: " p1_56",
      collectionid: "p1",
      question: "Они сейчас спят",
      answer: "They're slipping",
      note: "",
    },
    {
      id: " p1_57",
      collectionid: "p1",
      question: "Я сейчас готовлю",
      answer: "I'm cooking",
      note: "",
    },
    {
      id: " p1_58",
      collectionid: "p1",
      question: "Ты сейчас готовишь",
      answer: "you're cooking",
      note: "",
    },
    {
      id: " p1_59",
      collectionid: "p1",
      question: "Она сейчас готовит",
      answer: "She's cooking",
      note: "",
    },
    {
      id: " p1_60",
      collectionid: "p1",
      question: "Он сейчас готовит",
      answer: "He's cooking",
      note: "",
    },
    {
      id: " p1_61",
      collectionid: "p1",
      question: "Мы сейчас готовим",
      answer: "We're cooking",
      note: "",
    },
    {
      id: " p1_62",
      collectionid: "p1",
      question: "Вы сейчас готовите",
      answer: "You're cooking",
      note: "",
    },
    {
      id: " p1_63",
      collectionid: "p1",
      question: "Они сейчас готовят",
      answer: "They're cooking",
      note: "",
    },
    {
      id: " p1_64",
      collectionid: "p1",
      question: "Я сейчас иду",
      answer: "I'm going",
      note: "",
    },
    {
      id: " p1_65",
      collectionid: "p1",
      question: "Ты сейчас идешь",
      answer: "you're going",
      note: "",
    },
    {
      id: " p1_",
      collectionid: "p1",
      question: "Она сейчас идет",
      answer: "She's going",
      note: "",
    },
    {
      id: " p1_",
      collectionid: "p1",
      question: "Он сейчас идет",
      answer: "He's going",
      note: "",
    },
    {
      id: " p1_",
      collectionid: "p1",
      question: "Оно сейчас идет",
      answer: "It's going",
      note: "",
    },
    {
      id: " p1_",
      collectionid: "p1",
      question: "Мы сейчас идем",
      answer: "We're going",
      note: "",
    },
    {
      id: " p1_",
      collectionid: "p1",
      question: "Вы сейчас идете",
      answer: "You're going",
      note: "",
    },
    {
      id: " p1_",
      collectionid: "p1",
      question: "Они сейчас идут",
      answer: "They're going",
      note: "",
    },
    {
      id: " p2_0",
      collectionid: "p2",
      question: "Что я сейчас покупаю?",
      answer: "What am I buying?",
      note: "",
    },
    {
      id: " p2_1",
      collectionid: "p2",
      question: "Что ты сейчас покупаешь?",
      answer: "What are you buying?",
      note: "",
    },
    {
      id: " p2_2",
      collectionid: "p2",
      question: "Что она сейчас покупает?",
      answer: "What is she buying?",
      note: "",
    },
    {
      id: " p2_3",
      collectionid: "p2",
      question: "Что он сейчас покупает?",
      answer: "What is he buying?",
      note: "",
    },
    {
      id: " p2_4",
      collectionid: "p2",
      question: "Что мы сейчас покупаем?",
      answer: "What are we buying?",
      note: "",
    },
    {
      id: " p2_5",
      collectionid: "p2",
      question: "Что вы сейчас покупаете?",
      answer: "What are You buying?",
      note: "",
    },
    {
      id: " p2_6",
      collectionid: "p2",
      question: "Что они сейчас покупают?",
      answer: "What are they buying?",
      note: "",
    },
    {
      id: " p2_7",
      collectionid: "p2",
      question: "Что я сейчас читаю?",
      answer: "What am I reading?",
      note: "",
    },
    {
      id: " p2_8",
      collectionid: "p2",
      question: "Что ты сейчас читаешь?",
      answer: "What are you reading?",
      note: "",
    },
    {
      id: " p2_9",
      collectionid: "p2",
      question: "Что она сейчас читает?",
      answer: "What is she reading?",
      note: "",
    },
    {
      id: " p2_10",
      collectionid: "p2",
      question: "Что он сейчас читает?",
      answer: "What is he reading?",
      note: "",
    },
    {
      id: " p2_12",
      collectionid: "p2",
      question: "Что мы сейчас читаем?",
      answer: "What are we reading?",
      note: "",
    },
    {
      id: " p2_13",
      collectionid: "p2",
      question: "Что вы сейчас читаете?",
      answer: "What are You reading?",
      note: "",
    },
    {
      id: " p2_14",
      collectionid: "p2",
      question: "Что они сейчас читают?",
      answer: "What are they reading?",
      note: "",
    },
    {
      id: " p2_15",
      collectionid: "p2",
      question: "Что я сейчас выбираю?",
      answer: "What am I choosing?",
      note: "",
    },
    {
      id: " p2_16",
      collectionid: "p2",
      question: "Что ты сейчас выбираешь?",
      answer: "What are you choosing?",
      note: "",
    },
    {
      id: " p2_17",
      collectionid: "p2",
      question: "Что она сейчас выбирает?",
      answer: "What is she choosing?",
      note: "",
    },
    {
      id: " p2_18",
      collectionid: "p2",
      question: "Что он сейчас выбирает?",
      answer: "What is he choosing?",
      note: "",
    },
    {
      id: " p2_19",
      collectionid: "p2",
      question: "Что мы сейчас выбираем?",
      answer: "What are we choosing?",
      note: "",
    },
    {
      id: " p2_20",
      collectionid: "p2",
      question: "Что вы сейчас выбираете?",
      answer: "What are You choosing?",
      note: "",
    },
    {
      id: " p2_21",
      collectionid: "p2",
      question: "Что они сейчас выбирают?",
      answer: "What are they choosing?",
      note: "",
    },
    {
      id: " p2_22",
      collectionid: "p2",
      question: "Что я сейчас строю?",
      answer: "What am I building?",
      note: "",
    },
    {
      id: " p2_23",
      collectionid: "p2",
      question: "Что ты сейчас строишь?",
      answer: "What are you building?",
      note: "",
    },
    {
      id: " p2_24",
      collectionid: "p2",
      question: "Что она сейчас строит?",
      answer: "What is she building?",
      note: "",
    },
    {
      id: " p2_25",
      collectionid: "p2",
      question: "Что он сейчас строит?",
      answer: "What is he building?",
      note: "",
    },
    {
      id: " p2_26",
      collectionid: "p2",
      question: "Что мы сейчас строим?",
      answer: "What are we building?",
      note: "",
    },
    {
      id: " p2_27",
      collectionid: "p2",
      question: "Что вы сейчас строите?",
      answer: "What are You building?",
      note: "",
    },
    {
      id: " p2_28",
      collectionid: "p2",
      question: "Что они сейчас строят?",
      answer: "What are they building?",
      note: "",
    },
    {
      id: " p2_29",
      collectionid: "p2",
      question: "Что я сейчас готовлю?",
      answer: "What am I cooking?",
      note: "",
    },
    {
      id: " p2_30",
      collectionid: "p2",
      question: "Что ты сейчас готовишь?",
      answer: "What are you cooking?",
      note: "",
    },
    {
      id: " p2_31",
      collectionid: "p2",
      question: "Что она сейчас готовит?",
      answer: "What is she cooking?",
      note: "",
    },
    {
      id: " p2_32",
      collectionid: "p2",
      question: "Что он сейчас готовит?",
      answer: "What is he cooking?",
      note: "",
    },
    {
      id: " p2_33",
      collectionid: "p2",
      question: "Что мы сейчас готовим?",
      answer: "What are we cooking?",
      note: "",
    },
    {
      id: " p2_34",
      collectionid: "p2",
      question: "Что вы сейчас готовите?",
      answer: "What are You cooking?",
      note: "",
    },
    {
      id: " p2_35",
      collectionid: "p2",
      question: "Что они сейчас готовят?",
      answer: "What are they cooking?",
      note: "",
    },
    {
      id: " p2_36",
      collectionid: "p2",
      question: "Кто я?",
      answer: "Who am I?",
      note: "",
    },
    {
      id: " p2_37",
      collectionid: "p2",
      question: "Кто ты?",
      answer: "Who are you?",
      note: "",
    },
    {
      id: " p2_38",
      collectionid: "p2",
      question: "Кто она?",
      answer: "Who is she?",
      note: "",
    },
    {
      id: " p2_39",
      collectionid: "p2",
      question: "Кто он?",
      answer: "Who is he?",
      note: "",
    },
    {
      id: " p2_40",
      collectionid: "p2",
      question: "Кто это?",
      answer: "Who is it?",
      note: "",
    },
    {
      id: " p2_41",
      collectionid: "p2",
      question: "Кто мы?",
      answer: "Who are we?",
      note: "",
    },
    {
      id: " p2_42",
      collectionid: "p2",
      question: "Кто вы?",
      answer: "Who are You?",
      note: "",
    },
    {
      id: " p2_43",
      collectionid: "p2",
      question: "Кто они?",
      answer: "Who are they?",
      note: "",
    },
    {
      id: " p2_44",
      collectionid: "p2",
      question: "Она сейчас спит?",
      answer: "Is she slipping?",
      note: "",
    },
    {
      id: " p2_45",
      collectionid: "p2",
      question: "Как я сейчас готовлю?",
      answer: "How am I cooking?",
      note: "",
    },
    {
      id: " p2_46",
      collectionid: "p2",
      question: "Как ты сейчас готовишь?",
      answer: "How are you cooking?",
      note: "",
    },
    {
      id: " p2_47",
      collectionid: "p2",
      question: "Как она сейчас готовит?",
      answer: "How is she cooking?",
      note: "",
    },
    {
      id: " p2_48",
      collectionid: "p2",
      question: "Как он сейчас готовит?",
      answer: "How is he cooking?",
      note: "",
    },
    {
      id: " p2_49",
      collectionid: "p2",
      question: "Как мы сейчас готовим?",
      answer: "How are we cooking?",
      note: "",
    },
    {
      id: " p2_50",
      collectionid: "p2",
      question: "Как они сейчас готовят?",
      answer: "How are they cooking?",
      note: "",
    },
    {
      id: " p2_51",
      collectionid: "p2",
      question: "Где я сейчас прячусь?",
      answer: "Where am I hiding?",
      note: "",
    },
    {
      id: " p2_52",
      collectionid: "p2",
      question: "Где ты сейчас прячешься?",
      answer: "Where are you hiding?",
      note: "",
    },
    {
      id: " p2_53",
      collectionid: "p2",
      question: "Где она сейчас прячется?",
      answer: "Where is she hiding?",
      note: "",
    },
    {
      id: " p2_54",
      collectionid: "p2",
      question: "Где он сейчас прячется?",
      answer: "Where is he hiding?",
      note: "",
    },
    {
      id: " p2_55",
      collectionid: "p2",
      question: "Где оно сейчас прячется?",
      answer: "Where is it hiding?",
      note: "",
    },
    {
      id: " p2_56",
      collectionid: "p2",
      question: "Где мы сейчас прячемся?",
      answer: "Where are we hiding?",
      note: "",
    },
    {
      id: " p2_57",
      collectionid: "p2",
      question: "Где вы сейчас прячетесь?",
      answer: "Where are You hiding?",
      note: "",
    },
    {
      id: " p2_58",
      collectionid: "p2",
      question: "Где они сейчас прячутся?",
      answer: "Where are they hiding?",
      note: "",
    },
    {
      id: " p2_59",
      collectionid: "p2",
      question: "Куда я сейчас иду?",
      answer: "Where am I going?",
      note: "",
    },
    {
      id: " p2_60",
      collectionid: "p2",
      question: "Куда ты сейчас идешь?",
      answer: "Where are you going?",
      note: "",
    },
    {
      id: " p2_61",
      collectionid: "p2",
      question: "Куда она сейчас идет?",
      answer: "Where Is she going?",
      note: "",
    },
    {
      id: " p2_62",
      collectionid: "p2",
      question: "Куда он сейчас идет?",
      answer: "Where is he going?",
      note: "",
    },
    {
      id: " p2_63",
      collectionid: "p2",
      question: "Куда мы сейчас идем?",
      answer: "Where are we going?",
      note: "",
    },
    {
      id: " p2_64",
      collectionid: "p2",
      question: "Куда вы сейчас идете?",
      answer: "Where are You going?",
      note: "",
    },
    {
      id: " p2_65",
      collectionid: "p2",
      question: "Куда они сейчас идут?",
      answer: "Where are they going?",
      note: "",
    },
    {
      id: " p4_0",
      collectionid: "p4",
      question: "Что я сейчас...?",
      answer: "What am I...?",
      note: "",
    },
    {
      id: " p4_1",
      collectionid: "p4",
      question: "Что ты сейчас...?",
      answer: "What are you...?",
      note: "",
    },
    {
      id: " p4_2",
      collectionid: "p4",
      question: "Что мы сейчас...?",
      answer: "What are we...?",
      note: "",
    },
    {
      id: " p4_3",
      collectionid: "p4",
      question: "Что вы сейчас...?",
      answer: "What are You...?",
      note: "",
    },
    {
      id: " p4_4",
      collectionid: "p4",
      question: "Что они сейчас...?",
      answer: "What are they...?",
      note: "",
    },
    {
      id: " p4_5",
      collectionid: "p4",
      question: "Что она сейчас...?",
      answer: "What is she...?",
      note: "",
    },
    {
      Id: " p4_6",
      collectionid: "p4",
      question: "Что он сейчас...?",
      answer: "What is he...?",
      note: "",
    },
    {
      id: " p4_7",
      collectionid: "p4",
      question: "Что оно сейчас...?",
      answer: "What is it...?",
      note: "",
    },
    {
      id: " p4_8",
      collectionid: "p4",
      question: "Кто я...?",
      answer: "Who am I...?",
      note: "",
    },
    {
      id: " p4_9",
      collectionid: "p4",
      question: "Кто ты...?",
      answer: "Who are you...?",
      note: "",
    },
    {
      id: " p4_10",
      collectionid: "p4",
      question: "Кто мы...?",
      answer: "Who are we...?",
      note: "",
    },
    {
      id: " p4_11",
      collectionid: "p4",
      question: "Кто вы...?",
      answer: "Who are You...?",
      note: "",
    },
    {
      id: " p4_12",
      collectionid: "p4",
      question: "Кто они...?",
      answer: "Who are they...?",
      note: "",
    },
    {
      id: " p4_13",
      collectionid: "p4",
      question: "Кто она...?",
      answer: "Who is she...?",
      note: "",
    },
    {
      id: " p4_14",
      collectionid: "p4",
      question: "Кто он...?",
      answer: "Who is he...?",
      note: "",
    },
    {
      id: " p4_15",
      collectionid: "p4",
      question: "Как я сейчас...?",
      answer: "How am I...?",
      note: "",
    },
    {
      id: " p4_16",
      collectionid: "p4",
      question: "Как ты сейчас...?",
      answer: "How are you...?",
      note: "",
    },
    {
      id: " p4_17",
      collectionid: "p4",
      question: "Как мы сейчас...?",
      answer: "How are we...?",
      note: "",
    },
    {
      id: " p4_18",
      collectionid: "p4",
      question: "Как вы сейчас...?",
      answer: "How are You...?",
      note: "",
    },
    {
      id: " p4_19",
      collectionid: "p4",
      question: "Как они сейчас...?",
      answer: "How are they...?",
      note: "",
    },
    {
      id: " p4_20",
      collectionid: "p4",
      question: "Как она сейчас...?",
      answer: "How is she...?",
      note: "",
    },
    {
      id: " p4_21",
      collectionid: "p4",
      question: "Как он сейчас...?",
      answer: "How is he...?",
      note: "",
    },
    {
      id: " p4_22",
      collectionid: "p4",
      question: "Как оно сейчас...?",
      answer: "How is it...?",
      note: "",
    },
    {
      id: " p4_23",
      collectionid: "p4",
      question: "Где я сейчас...?",
      answer: "Where am I...?",
      note: "",
    },
    {
      id: " p4_24",
      collectionid: "p4",
      question: "Где ты сейчас...?",
      answer: "Where are you...?",
      note: "",
    },
    {
      id: " p4_25",
      collectionid: "p4",
      question: "Где мы сейчас...?",
      answer: "Where are we...?",
      note: "",
    },
    {
      id: " p4_26",
      collectionid: "p4",
      question: "Где вы сейчас...?",
      answer: "Where are You...?",
      note: "",
    },
    {
      id: " p4_27",
      collectionid: "p4",
      question: "Где они сейчас...?",
      answer: "Where are they...?",
      note: "",
    },
    {
      id: " p4_28",
      collectionid: "p4",
      question: "Где она сейчас...?",
      answer: "Where is she...?",
      note: "",
    },
    {
      id: " p4_29",
      collectionid: "p4",
      question: "Где он сейчас...?",
      answer: "Where is he...?",
      note: "",
    },
    {
      id: " p4_30",
      collectionid: "p4",
      question: "Где оно сейчас...?",
      answer: "Where is it...?",
      note: "",
    },
    {
      id: " p4_31",
      collectionid: "p4",
      question: "Куда Я сейчас...?",
      answer: "Where am I...?",
      note: "",
    },
    {
      id: " p4_32",
      collectionid: "p4",
      question: "Куда ты сейчас...?",
      answer: "Where are you...?",
      note: "",
    },
    {
      id: " p4_33",
      collectionid: "p4",
      question: "Куда мы сейчас...?",
      answer: "Where are we...?",
      note: "",
    },
    {
      id: " p4_34",
      collectionid: "p4",
      question: "Куда вы сейчас...?",
      answer: "Where are You...?",
      note: "",
    },
    {
      id: " p4_35",
      collectionid: "p4",
      question: "Куда они сейчас...?",
      answer: "Where are they...?",
      note: "",
    },
    {
      id: " p4_36",
      collectionid: "p4",
      question: "Куда она сейчас...?",
      answer: "Where is she...?",
      note: "",
    },
    {
      id: " p4_37",
      collectionid: "p4",
      question: "Куда он сейчас...?",
      answer: "Where is he...?",
      note: "",
    },
    {
      id: " p4_38",
      collectionid: "p4",
      question: "Куда оно сейчас...?",
      answer: "Where is it...?",
      note: "",
    },
    {
      id: " p5_0",
      collectionid: "p5",
      question: "Я иногда хожу",
      answer: "Sometimes I go ",
      note: "",
    },
    {
      id: " p5_1",
      collectionid: "p5",
      question: "Ты иногда ходишь",
      answer: "Sometimes you go ",
      note: "",
    },
    {
      id: " p5_2",
      collectionid: "p5",
      question: "Мы иногда ходим",
      answer: "Sometimes we go ",
      note: "",
    },
    {
      id: " p5_3",
      collectionid: "p5",
      question: "Вы иногда ходите",
      answer: "Sometimes You go ",
      note: "",
    },
    {
      id: " p5_4",
      collectionid: "p5",
      question: "Они иногда ходят",
      answer: "Sometimes they go ",
      note: "",
    },
    {
      id: " p5_5",
      collectionid: "p5",
      question: "Она иногда ходит",
      answer: "Sometimes she goes ",
      note: "",
    },
    {
      id: " p5_6",
      collectionid: "p5",
      question: "Он иногда ходит",
      answer: "Sometimes he goes ",
      note: "",
    },
    {
      id: " p5_7",
      collectionid: "p5",
      question: "Я всегда знаю",
      answer: "I always know ",
      note: "",
    },
    {
      id: " p5_8",
      collectionid: "p5",
      question: "Ты всегда знаешь",
      answer: "you always know ",
      note: "",
    },
    {
      id: " p5_9",
      collectionid: "p5",
      question: "Мы всегда знаем",
      answer: "We always know ",
      note: "",
    },
    {
      id: " p5_10",
      collectionid: "p5",
      question: "Вы всегда знаете",
      answer: "You always know ",
      note: "",
    },
    {
      id: " p5_11",
      collectionid: "p5",
      question: "Они всегда знают",
      answer: "They always know ",
      note: "",
    },
    {
      id: " p5_12",
      collectionid: "p5",
      question: "Она всегда знает",
      answer: "She always knows ",
      note: "",
    },
    {
      id: " p5_13",
      collectionid: "p5",
      question: "Он всегда знает",
      answer: "He always knows ",
      note: "",
    },
    {
      id: " p5_14",
      collectionid: "p5",
      question: "Я часто готовлю",
      answer: "I often cook ",
      note: "",
    },
    {
      id: " p5_15",
      collectionid: "p5",
      question: "Ты часто готовишь",
      answer: "you often cook ",
      note: "",
    },
    {
      id: " p5_16",
      collectionid: "p5",
      question: "Мы часто готовим",
      answer: "We often cook ",
      note: "",
    },
    {
      id: " p5_17",
      collectionid: "p5",
      question: "Вы часто готовите",
      answer: "You often cook ",
      note: "",
    },
    {
      id: " p5_18",
      collectionid: "p5",
      question: "Они часто готовят",
      answer: "They often cook ",
      note: "",
    },
    {
      id: " p5_19",
      collectionid: "p5",
      question: "Она часто готовит",
      answer: "She often cooks ",
      note: "",
    },
    {
      id: " p5_20",
      collectionid: "p5",
      question: "Он часто готовит",
      answer: "He often cooks ",
      note: "",
    },
    {
      id: " p5_21",
      collectionid: "p5",
      question: "Я никогда не делаю",
      answer: "I never do ",
      note: "",
    },
    {
      id: " p5_22",
      collectionid: "p5",
      question: "Ты никогда не делаешь",
      answer: "you never do ",
      note: "",
    },
    {
      id: " p5_23",
      collectionid: "p5",
      question: "Мы никогда не делаем",
      answer: "We never do ",
      note: "",
    },
    {
      id: " p5_24",
      collectionid: "p5",
      question: "Вы никогда не делаете",
      answer: "You never do ",
      note: "",
    },
    {
      id: " p5_25",
      collectionid: "p5",
      question: "Они никогда не делают",
      answer: "They never do ",
      note: "",
    },
    {
      id: " p5_26",
      collectionid: "p5",
      question: "Она никогда не делает",
      answer: "She never does ",
      note: "",
    },
    {
      id: " p5_27",
      collectionid: "p5",
      question: "Он никогда не делает",
      answer: "He never does ",
      note: "",
    },
    {
      id: " p5_28",
      collectionid: "p5",
      question: "Я никогда не знаю",
      answer: "I never know ",
      note: "",
    },
    {
      id: " p5_29",
      collectionid: "p5",
      question: "Ты никогда не знаешь",
      answer: "you never know ",
      note: "",
    },
    {
      id: " p5_30",
      collectionid: "p5",
      question: "Мы никогда не знаем",
      answer: "We never know ",
      note: "",
    },
    {
      id: " p5_31",
      collectionid: "p5",
      question: "Вы никогда не знаете",
      answer: "You never know ",
      note: "",
    },
    {
      id: " p5_32",
      collectionid: "p5",
      question: "Они никогда не знают",
      answer: "They never know ",
      note: "",
    },
    {
      id: " p5_33",
      collectionid: "p5",
      question: "Она никогда не знает",
      answer: "She never knows ",
      note: "",
    },
    {
      id: " p5_34",
      collectionid: "p5",
      question: "Он никогда не знает",
      answer: "He never knows ",
      note: "",
    },
    {
      id: " p5_35",
      collectionid: "p5",
      question: "Я редко читаю",
      answer: "I rarely read ",
      note: "",
    },
    {
      id: " p5_36",
      collectionid: "p5",
      question: "Ты редко читаешь",
      answer: "you rarely read ",
      note: "",
    },
    {
      id: " p5_37",
      collectionid: "p5",
      question: "Мы редко читаем",
      answer: "We rarely read ",
      note: "",
    },
    {
      id: " p5_38",
      collectionid: "p5",
      question: "Вы редко читаете",
      answer: "You rarely read ",
      note: "",
    },
    {
      id: " p5_39",
      collectionid: "p5",
      question: "Они редко читают",
      answer: "They rarely read ",
      note: "",
    },
    {
      id: " p5_40",
      collectionid: "p5",
      question: "Она редко читает",
      answer: "She rarely reads ",
      note: "",
    },
    {
      id: " p5_41",
      collectionid: "p5",
      question: "Он редко читает",
      answer: "He rarely reads ",
      note: "",
    },
    {
      id: " p5_42",
      collectionid: "p5",
      question: "Я всегда работаю",
      answer: "I always work ",
      note: "",
    },
    {
      id: " p5_43",
      collectionid: "p5",
      question: "Ты всегда работаешь",
      answer: "you always work ",
      note: "",
    },
    {
      id: " p5_44",
      collectionid: "p5",
      question: "Мы всегда работаем",
      answer: "We always work ",
      note: "",
    },
    {
      id: " p5_45",
      collectionid: "p5",
      question: "Вы всегда работаете",
      answer: "You always work ",
      note: "",
    },
    {
      id: " p5_46",
      collectionid: "p5",
      question: "Они всегда работают",
      answer: "They always work ",
      note: "",
    },
    {
      id: " p5_47",
      collectionid: "p5",
      question: "Она всегда работает",
      answer: "She always works ",
      note: "",
    },
    {
      id: " p5_48",
      collectionid: "p5",
      question: "Он всегда работает",
      answer: "He always works ",
      note: "",
    },
    {
      id: " p5_49",
      collectionid: "p5",
      question: "Это всегда работает",
      answer: "It always works ",
      note: "",
    },
    {
      id: " p6_0",
      collectionid: "p6",
      question: "Когда я обычно готовлю?",
      answer: "When do I ussualy cook?",
      note: "",
    },
    {
      id: " p6_1",
      collectionid: "p6",
      question: "Когда ты обычно готовишь?",
      answer: "When do you ussualy cook?",
      note: "",
    },
    {
      id: " p6_2",
      collectionid: "p6",
      question: "Когда мы обычно готовим?",
      answer: "When do we ussualy cook?",
      note: "",
    },
    {
      id: " p6_3",
      collectionid: "p6",
      question: "Когда вы обычно готовите?",
      answer: "When do You ussualy cook?",
      note: "",
    },
    {
      id: " p6_4",
      collectionid: "p6",
      question: "Когда они обычно готовят?",
      answer: "When do they ussualy cook?",
      note: "",
    },
    {
      id: " p6_5",
      collectionid: "p6",
      question: "Когда она обычно готовит?",
      answer: "When does she ussualy cook?",
      note: "",
    },
    {
      id: " p6_6",
      collectionid: "p6",
      question: "Когда он обычно готовит?",
      answer: "When does he ussualy cook?",
      note: "",
    },
    {
      id: " p6_7",
      collectionid: "p6",
      question: "Когда он обычно приходит?",
      answer: "When does it ussualy come?",
      note: "",
    },
    {
      id: " p6_8",
      collectionid: "p6",
      question: "Где я всегда прячусь?",
      answer: "Where do I always hide?",
      note: "",
    },
    {
      id: " p6_9",
      collectionid: "p6",
      question: "Где ты всегда прячешься?",
      answer: "Where do you always hide?",
      note: "",
    },
    {
      id: " p6_10",
      collectionid: "p6",
      question: "Где мы всегда прячемся?",
      answer: "Where do WE always hide?",
      note: "",
    },
    {
      id: " p6_11",
      collectionid: "p6",
      question: "Где вы всегда прячетесь?",
      answer: "Where do You always hide?",
      note: "",
    },
    {
      id: " p6_12",
      collectionid: "p6",
      question: "Где они всегда прячутся?",
      answer: "Where do they always hide?",
      note: "",
    },
    {
      id: " p6_13",
      collectionid: "p6",
      question: "Где она всегда прячется?",
      answer: "Where does she always hide?",
      note: "",
    },
    {
      id: " p6_14",
      collectionid: "p6",
      question: "Где он всегда прячется?",
      answer: "Where does he always hide?",
      note: "",
    },
    {
      id: " p6_15",
      collectionid: "p6",
      question: "Где оно всегда прячется?",
      answer: "Where does it always hide?",
      note: "",
    },
    {
      id: " p6_16",
      collectionid: "p6",
      question: "Что Я часто покупаю?",
      answer: "What do I often buy?",
      note: "",
    },
    {
      id: " p6_17",
      collectionid: "p6",
      question: "Что ты часто покупаешь?",
      answer: "What do you often buy?",
      note: "",
    },
    {
      id: " p6_18",
      collectionid: "p6",
      question: "Что мы часто покупаем?",
      answer: "What do we often buy?",
      note: "",
    },
    {
      id: " p6_19",
      collectionid: "p6",
      question: "Что вы часто покупаете?",
      answer: "What do You often buy?",
      note: "",
    },
    {
      id: " p6_20",
      collectionid: "p6",
      question: "Что они часто покупают?",
      answer: "What do they often buy?",
      note: "",
    },
    {
      id: " p6_21",
      collectionid: "p6",
      question: "Что она часто покупает?",
      answer: "What does she often buy?",
      note: "",
    },
    {
      id: " p6_22",
      collectionid: "p6",
      question: "Что он часто покупает?",
      answer: "What does he often buy?",
      note: "",
    },
    {
      id: " p6_23",
      collectionid: "p6",
      question: "Что она часто делает?",
      answer: "What does she often do?",
      note: "",
    },
    {
      id: " p6_24",
      collectionid: "p6",
      question: "Кого я иногда встречаю?",
      answer: "Who do I sometimes meet?",
      note: "",
    },
    {
      id: " p6_25",
      collectionid: "p6",
      question: "Кого ты иногда встречаешь?",
      answer: "Who do you sometimes meet?",
      note: "",
    },
    {
      id: " p6_26",
      collectionid: "p6",
      question: "Кого мы иногда встречаем?",
      answer: "Who do we sometimes meet?",
      note: "",
    },
    {
      id: " p6_27",
      collectionid: "p6",
      question: "Кого вы иногда встречаете?",
      answer: "Who do You sometimes meet?",
      note: "",
    },
    {
      id: " p6_28",
      collectionid: "p6",
      question: "Кого они иногда встречают?",
      answer: "Who do they sometimes meet?",
      note: "",
    },
    {
      id: " p6_29",
      collectionid: "p6",
      question: "Кого она иногда встречает?",
      answer: "Who does she sometimes meet?",
      note: "",
    },
    {
      id: " p6_30",
      collectionid: "p6",
      question: "Кого он иногда встречает?",
      answer: "Who does he sometimes meet?",
      note: "",
    },
    {
      id: " p6_31",
      collectionid: "p6",
      question: "Кого оно иногда встречает?",
      answer: "Who does it sometimes meet?",
      note: "",
    },
    {
      id: " p6_32",
      collectionid: "p6",
      question: " Я вообще пью?",
      answer: "Do I ever drink?",
      note: "",
    },
    {
      id: " p6_33",
      collectionid: "p6",
      question: " Ты вообще пьешь?",
      answer: "Do you ever drink?",
      note: "",
    },
    {
      Id: " p6_34",
      collectionid: "p6",
      question: " Мы вообще пьем?",
      answer: "Do we ever drink?",
      note: "",
    },
    {
      id: " p6_35",
      collectionid: "p6",
      question: " Вы вообще пьете?",
      answer: "Do You ever drink?",
      note: "",
    },
    {
      id: " p6_36",
      collectionid: "p6",
      question: " Они вообще пьют?",
      answer: "Do they ever drink?",
      note: "",
    },
    {
      id: " p6_37",
      collectionid: "p6",
      question: " Она вообще пьет?",
      answer: "Does she ever drink?",
      note: "",
    },
    {
      id: " p6_38",
      collectionid: "p6",
      question: " Он вообще пьет?",
      answer: "Does he ever drink?",
      note: "",
    },
    {
      id: " p6_39",
      collectionid: "p6",
      question: " Он вообще спит?",
      answer: "Does he ever slip?",
      note: "",
    },
    {
      id: " p6_40",
      collectionid: "p6",
      question: "Как я обычно сплю?",
      answer: "How do I ussualy slip?",
      note: "",
    },
    {
      id: " p6_41",
      collectionid: "p6",
      question: "Как ты обычно спишь?",
      answer: "How do you ussualy slip?",
      note: "",
    },
    {
      id: " p6_42",
      collectionid: "p6",
      question: "Как мы обычно спим?",
      answer: "How do we ussualy slip?",
      note: "",
    },
    {
      Id: " p6_43",
      collectionid: "p6",
      question: "Как вы обычно спите?",
      answer: "How do You ussualy slip?",
      note: "",
    },
    {
      Id: " p6_44",
      collectionid: "p6",
      question: "Как они обычно спят?",
      answer: "How do they ussualy slip?",
      note: "",
    },
    {
      id: " p6_45",
      collectionid: "p6",
      question: "Как она обычно спит?",
      answer: "How does she ussualy slip?",
      note: "",
    },
    {
      id: " p6_46",
      collectionid: "p6",
      question: "Как он обычно спит?",
      answer: "How does he ussualy slip?",
      note: "",
    },
    {
      id: " p6_47",
      collectionid: "p6",
      question: "Как оно обычно спит?",
      answer: "How does it ussualy slip?",
      note: "",
    },
    {
      id: " p6_48",
      collectionid: "p6",
      question: "Куда я редко хожу?",
      answer: "Where do I rarely go?",
      note: "",
    },
    {
      id: " p6_49",
      collectionid: "p6",
      question: "Куда ты редко ходишь?",
      answer: "Where do you rarely go?",
      note: "",
    },
    {
      id: " p6_50",
      collectionid: "p6",
      question: "Куда мы редко ходим?",
      answer: "Where do we rarely go?",
      note: "",
    },
    {
      id: " p6_51",
      collectionid: "p6",
      question: "Куда вы редко ходите?",
      answer: "Where do You rarely go?",
      note: "",
    },
    {
      id: " p6_52",
      collectionid: "p6",
      question: "Куда они редко ходят?",
      answer: "Where do they rarely go?",
      note: "",
    },
    {
      id: " p6_53",
      collectionid: "p6",
      question: "Куда Она редко ходит?",
      answer: "Where does She rarely go?",
      note: "",
    },
    {
      id: " p6_54",
      collectionid: "p6",
      question: "Куда он редко ходит?",
      answer: "Where does he rarely go?",
      note: "",
    },
    {
      id: " p6_55",
      collectionid: "p6",
      question: "Куда оно редко ходит?",
      answer: "Where does it rarely go?",
      note: "",
    },
    {
      id: " p7_0",
      collectionid: "p7",
      question: "Когда я обычно...?",
      answer: "When do I ussualy...?",
      note: "",
    },
    {
      id: " p7_1",
      collectionid: "p7",
      question: "Когда ты обычно...?",
      answer: "When do you ussualy...?",
      note: "",
    },
    {
      id: " p7_2",
      collectionid: "p7",
      question: "Когда мы обычно...?",
      answer: "When do we ussualy...?",
      note: "",
    },
    {
      id: " p7_3",
      collectionid: "p7",
      question: "Когда вы обычно...?",
      answer: "When do You ussualy...?",
      note: "",
    },
    {
      id: " p7_4",
      collectionid: "p7",
      question: "Когда они обычно...?",
      answer: "When do they ussualy...?",
      note: "",
    },
    {
      id: " p7_5",
      collectionid: "p7",
      question: "Когда она обычно...?",
      answer: "When does she ussualy...?",
      note: "",
    },
    {
      id: " p7_6",
      collectionid: "p7",
      question: "Когда он обычно...?",
      answer: "When does he ussualy...?",
      note: "",
    },
    {
      id: " p7_7",
      collectionid: "p7",
      question: "Когда оно обычно...?",
      answer: "When does it ussualy...?",
      note: "",
    },
    {
      id: " p7_8",
      collectionid: "p7",
      question: "Кого я обычно...?",
      answer: "Who do I ussualy...?",
      note: "",
    },
    {
      id: " p7_9",
      collectionid: "p7",
      question: "Кого ты обычно...?",
      answer: "Who do you ussualy...?",
      note: "",
    },
    {
      id: " p7_10",
      collectionid: "p7",
      question: "Кого мы обычно...?",
      answer: "Who do we ussualy...?",
      note: "",
    },
    {
      id: " p7_11",
      collectionid: "p7",
      question: "Кого вы обычно...?",
      answer: "Who do You ussualy...?",
      note: "",
    },
    {
      id: " p7_12",
      collectionid: "p7",
      question: "Кого они обычно...?",
      answer: "Who do they ussualy...?",
      note: "",
    },
    {
      id: " p7_13",
      collectionid: "p7",
      question: "Кого она обычно...?",
      answer: "Who does she ussualy...?",
      note: "",
    },
    {
      id: " p7_14",
      collectionid: "p7",
      question: "Кого Он обычно...?",
      answer: "Who does he ussualy...?",
      note: "",
    },
    {
      id: " p7_15",
      collectionid: "p7",
      question: "Кого Оно обычно...?",
      answer: "Who does it ussualy...?",
      note: "",
    },
    {
      id: " p7_16",
      collectionid: "p7",
      question: "Что я всегда...?",
      answer: "What do I always...?",
      note: "",
    },
    {
      id: " p7_17",
      collectionid: "p7",
      question: "Что ты всегда...?",
      answer: "What do you always...?",
      note: "",
    },
    {
      id: " p7_18",
      collectionid: "p7",
      question: "Что мы всегда...?",
      answer: "What do we always...?",
      note: "",
    },
    {
      id: " p7_19",
      collectionid: "p7",
      question: "Что вы всегда...?",
      answer: "What do You always...?",
      note: "",
    },
    {
      id: " p7_20",
      collectionid: "p7",
      question: "Что они всегда...?",
      answer: "What do they always...?",
      note: "",
    },
    {
      id: " p7_21",
      collectionid: "p7",
      question: "Что она всегда...?",
      answer: "What does she always...?",
      note: "",
    },
    {
      id: " p7_22",
      collectionid: "p7",
      question: "Что он всегда...?",
      answer: "What does he always...?",
      note: "",
    },
    {
      id: " p7_23",
      collectionid: "p7",
      question: "Что оно всегда...?",
      answer: "What does it always...?",
      note: "",
    },
    {
      id: " p7_24",
      collectionid: "p7",
      question: "Куда я редко...?",
      answer: "Where do I rarely...?",
      note: "",
    },
    {
      id: " p7_25",
      collectionid: "p7",
      question: "Куда ты редко...?",
      answer: "Where do you rarely...?",
      note: "",
    },
    {
      id: " p7_26",
      collectionid: "p7",
      question: "Куда мы редко...?",
      answer: "Where do we rarely...?",
      note: "",
    },
    {
      id: " p7_27",
      collectionid: "p7",
      question: "Куда вы редко...?",
      answer: "Where do You rarely...?",
      note: "",
    },
    {
      id: " p7_28",
      collectionid: "p7",
      question: "Куда они редко...?",
      answer: "Where do they rarely...?",
      note: "",
    },
    {
      id: " p7_29",
      collectionid: "p7",
      question: "Куда она редко...?",
      answer: "Where does she rarely...?",
      note: "",
    },
    {
      id: " p7_30",
      collectionid: "p7",
      question: "Куда он редко...?",
      answer: "Where does he rarely...?",
      note: "",
    },
    {
      id: " p7_31",
      collectionid: "p7",
      question: "Где оно редко...?",
      answer: "Where does it rarely...?",
      note: "",
    },
    {
      id: " p7_32",
      collectionid: "p7",
      question: "Где я часто...?",
      answer: "Where do I often...?",
      note: "",
    },
    {
      id: " p7_33",
      collectionid: "p7",
      question: "Где ты часто...?",
      answer: "Where do you often...?",
      note: "",
    },
    {
      id: " p7_34",
      collectionid: "p7",
      question: "Где мы часто...?",
      answer: "Where do we often...?",
      note: "",
    },
    {
      id: " p7_35",
      collectionid: "p7",
      question: "Где вы часто...?",
      answer: "Where do you often...?",
      note: "",
    },
    {
      Id: " p7_36",
      collectionid: "p7",
      question: "Где они часто...?",
      answer: "Where do they often...?",
      note: "",
    },
    {
      id: " p7_37",
      collectionid: "p7",
      question: "Где она часто...?",
      answer: "Where does she often...?",
      note: "",
    },
    {
      id: " p7_38",
      collectionid: "p7",
      question: "Где он часто...?",
      answer: "Where does he often...?",
      note: "",
    },
    {
      id: " p7_39",
      collectionid: "p7",
      question: "Где оно часто...?",
      answer: "Where does it often...?",
      note: "",
    },
    {
      id: " p7_40",
      collectionid: "p7",
      question: " Я вообще...?",
      answer: "do I ever...?",
      note: "",
    },
    {
      id: " p7_41",
      collectionid: "p7",
      question: " Ты вообще...?",
      answer: "do you ever...?",
      note: "",
    },
    {
      id: " p7_42",
      collectionid: "p7",
      question: " Мы вообще...?",
      answer: "do we ever...?",
      note: "",
    },
    {
      id: " p7_43",
      collectionid: "p7",
      question: " Вы вообще...?",
      answer: "do you ever...?",
      note: "",
    },
    {
      id: " p7_44",
      collectionid: "p7",
      question: " Они вообще...?",
      answer: "do they ever...?",
      note: "",
    },
    {
      id: " p7_45",
      collectionid: "p7",
      question: " Она вообще...?",
      answer: "does she ever...?",
      note: "",
    },
    {
      id: " p7_46",
      collectionid: "p7",
      question: " Он вообще...?",
      answer: "does he ever...?",
      note: "",
    },
    {
      id: " p7_47",
      collectionid: "p7",
      question: " Оно вообще...?",
      answer: "does it ever...?",
      note: "",
    },
    {
      id: " p7_48",
      collectionid: "p7",
      question: "Куда  я иногда...?",
      answer: "Where do I sometimes...?",
      note: "",
    },
    {
      id: " p7_49",
      collectionid: "p7",
      question: "Куда ты иногда...?",
      answer: "Where do you sometimes...?",
      note: "",
    },
    {
      id: " p7_50",
      collectionid: "p7",
      question: "Куда мы иногда...?",
      answer: "Where do we sometimes...?",
      note: "",
    },
    {
      id: " p7_51",
      collectionid: "p7",
      question: "Куда вы иногда...?",
      answer: "Where do You sometimes...?",
      note: "",
    },
    {
      id: " p7_52",
      collectionid: "p7",
      question: "Куда они иногда...?",
      answer: "Where do they sometimes...?",
      note: "",
    },
    {
      id: " p7_53",
      collectionid: "p7",
      question: "Куда она иногда...?",
      answer: "Where does she sometimes...?",
      note: "",
    },
    {
      id: " p7_54",
      collectionid: "p7",
      question: "Куда он иногда...?",
      answer: "Where does he sometimes...?",
      note: "",
    },
    {
      id: " p7_55",
      collectionid: "p7",
      question: "Куда оно иногда...?",
      answer: "Where does it sometimes...?",
      note: "",
    },
    {
      id: " p7_56",
      collectionid: "p7",
      question: "Когда  я часто...?",
      answer: "When do I ussualy...?",
      note: "",
    },
    {
      id: " p7_57",
      collectionid: "p7",
      question: "Когда ты часто...?",
      answer: "When do you often...?",
      note: "",
    },
    {
      id: " p7_58",
      collectionid: "p7",
      question: "Когда мы часто...?",
      answer: "When do we often...?",
      note: "",
    },
    {
      id: " p7_59",
      collectionid: "p7",
      question: "Когда вы часто...?",
      answer: "When do You often...?",
      note: "",
    },
    {
      id: " p7_60",
      collectionid: "p7",
      question: "Когда они часто...?",
      answer: "When do they often...?",
      note: "",
    },
    {
      id: " p7_61",
      collectionid: "p7",
      question: "Когда она часто...?",
      answer: "When does she often...?",
      note: "",
    },
    {
      id: " p7_62",
      collectionid: "p7",
      question: "Когда он часто...?",
      answer: "When does he often...?",
      note: "",
    },
    {
      id: " p7_63",
      collectionid: "p7",
      question: "Когда оно часто...?",
      answer: "When does it often...?",
      note: "",
    },
    {
      id: "p8_0",
      collectionid: "p8",
      question: "Почему я злюсь?",
      answer: "Why am I angry?",
      note: "",
    },
    {
      id: "p8_1",
      collectionid: "p8",
      question: "Почему ты злишься?",
      answer: "Why are you angry?",
      note: "",
    },
    {
      id: "p8_2",
      collectionid: "p8",
      question: "Почему мы злимся?",
      answer: "Why are we angry?",
      note: "",
    },
    {
      id: "p8_3",
      collectionid: "p8",
      question: "Почему вы злитесь?",
      answer: "Why are You angry?",
      note: "",
    },
    {
      id: "p8_4",
      collectionid: "p8",
      question: "Почему они злятся?",
      answer: "Why are they angry?",
      note: "",
    },
    {
      id: "p8_5",
      collectionid: "p8",
      question: "Почему она злится?",
      answer: "Why is she angry?",
      note: "",
    },
    {
      id: "p8_6",
      collectionid: "p8",
      question: "Почему он злится?",
      answer: "Why is he angry?",
      note: "",
    },
    {
      id: "p8_7",
      collectionid: "p8",
      question: "Когда я счастливый?",
      answer: "When am I happy?",
      note: "",
    },
    {
      id: "p8_8",
      collectionid: "p8",
      question: "Когда ты счастливый?",
      answer: "When are you happy?",
      note: "",
    },
    {
      id: "p8_9",
      collectionid: "p8",
      question: "Когда мы счастливые?",
      answer: "When are we happy?",
      note: "",
    },
    {
      id: "p8_10",
      collectionid: "p8",
      question: "Когда вы счастливые?",
      answer: "When are You happy?",
      note: "",
    },
    {
      id: "p8_11",
      collectionid: "p8",
      question: "Когда они счастливые?",
      answer: "When are they happy?",
      note: "",
    },
    {
      id: "p8_12",
      collectionid: "p8",
      question: "Когда она счастливая?",
      answer: "When is she happy?",
      note: "",
    },
    {
      id: "p8_13",
      collectionid: "p8",
      question: "Когда он счастливый?",
      answer: "When is he happy?",
      note: "",
    },
    {
      id: "p8_14",
      collectionid: "p8",
      question: " Я голодный?",
      answer: " Am I hungry?",
      note: "",
    },
    {
      id: "p8_15",
      collectionid: "p8",
      question: " Ты голодный?",
      answer: " Are you hungry?",
      note: "",
    },
    {
      id: "p8_16",
      collectionid: "p8",
      question: " Мы голодные?",
      answer: " Are we hungry?",
      note: "",
    },
    {
      id: "p8_17",
      collectionid: "p8",
      question: " Вы голодные?",
      answer: " Are you hungry?",
      note: "",
    },
    {
      id: "p8_18",
      collectionid: "p8",
      question: " Они голодные?",
      answer: " Are they hungry?",
      note: "",
    },
    {
      id: "p8_19",
      collectionid: "p8",
      question: " Она голодная?",
      answer: " Is she hungry?",
      note: "",
    },
    {
      id: "p8_20",
      collectionid: "p8",
      question: " Он голодный?",
      answer: " Is he hungry?",
      note: "",
    },
    {
      id: "p8_21",
      collectionid: "p8",
      question: " Я плохой?",
      answer: " Am I bad?",
      note: "",
    },
    {
      id: "p8_22",
      collectionid: "p8",
      question: " Ты плохой?",
      answer: " Are you bad?",
      note: "",
    },
    {
      id: "p8_23",
      collectionid: "p8",
      question: " Ты хороший?",
      answer: " Are you good?",
      note: "",
    },
    {
      id: "p8_24",
      collectionid: "p8",
      question: " Вы плохие?",
      answer: " Are you bad?",
      note: "",
    },
    {
      id: "p8_25",
      collectionid: "p8",
      question: " Они плохие?",
      answer: " Are they bad?",
      note: "",
    },
    {
      id: "p8_26",
      collectionid: "p8",
      question: " Она плохая?",
      answer: " Is she bad?",
      note: "",
    },
    {
      id: "p8_27",
      collectionid: "p8",
      question: " Он плохой?",
      answer: " Is he bad?",
      note: "",
    },
    {
      id: "p8_28",
      collectionid: "p8",
      question: " Это плохо?",
      answer: " Is it bad?",
      note: "",
    },
    {
      id: "p8_29",
      collectionid: "p8",
      question: " Я дома?",
      answer: " Am I at home?",
      note: "",
    },
    {
      id: "p8_30",
      collectionid: "p8",
      question: " Ты дома?",
      answer: " Are you at home?",
      note: "",
    },
    {
      id: "p8_31",
      collectionid: "p8",
      question: " Мы дома?",
      answer: " Are we at home?",
      note: "",
    },
    {
      id: "p8_32",
      collectionid: "p8",
      question: " Вы дома?",
      answer: " Are you at home?",
      note: "",
    },
    {
      id: "p8_33",
      collectionid: "p8",
      question: " Они дома?",
      answer: " Are they at home?",
      note: "",
    },
    {
      id: "p8_34",
      collectionid: "p8",
      question: " Она дома?",
      answer: " Is she at home?",
      note: "",
    },
    {
      id: "p8_35",
      collectionid: "p8",
      question: " Он дома?",
      answer: " Is he at home?",
      note: "",
    },
    {
      id: "p8_36",
      collectionid: "p8",
      question: " Это дома?",
      answer: " Is it at home?",
      note: "",
    },
    {
      id: "p8_37",
      collectionid: "p8",
      question: " Я на работе?",
      answer: " Am I at work?",
      note: "",
    },
    {
      id: "p8_38",
      collectionid: "p8",
      question: " Ты на работе?",
      answer: " Are you at work?",
      note: "",
    },
    {
      id: "p8_39",
      collectionid: "p8",
      question: " Мы на работе?",
      answer: " Are we at work?",
      note: "",
    },
    {
      id: "p8_40",
      collectionid: "p8",
      question: " Вы на работе?",
      answer: " Are You at work?",
      note: "",
    },
    {
      id: "p8_41",
      collectionid: "p8",
      question: " Они на работе?",
      answer: " Are they at work?",
      note: "",
    },
    {
      id: "p8_42",
      collectionid: "p8",
      question: " Она на работе?",
      answer: " Is she at work?",
      note: "",
    },
    {
      id: "p8_43",
      collectionid: "p8",
      question: " Он на работе?",
      answer: " Is he at work?",
      note: "",
    },
    {
      id: "p8_44",
      collectionid: "p8",
      question: " Это на работе?",
      answer: " Is it at work?",
      note: "",
    },
    {
      id: "p9_0",
      collectionid: "p9",
      question: "Я болею",
      answer: "I am ill ",
      note: "",
    },
    {
      id: "p9_1",
      collectionid: "p9",
      question: "Ты болеешь",
      answer: "you are ill ",
      note: "",
    },
    {
      id: "p9_2",
      collectionid: "p9",
      question: "Мы болеем",
      answer: "We are ill ",
      note: "",
    },
    {
      id: "p9_3",
      collectionid: "p9",
      question: "Вы болеете",
      answer: "You are ill ",
      note: "",
    },
    {
      id: "p9_4",
      collectionid: "p9",
      question: "Они болеют",
      answer: "They are ill ",
      note: "",
    },
    {
      id: "p9_5",
      collectionid: "p9",
      question: "Она болеет",
      answer: "She is ill ",
      note: "",
    },
    {
      id: "p9_6",
      collectionid: "p9",
      question: "Он болеет",
      answer: "He is ill ",
      note: "",
    },
    {
      id: "p9_7",
      collectionid: "p9",
      question: "Оно болеет",
      answer: "It is ill ",
      note: "",
    },
    {
      id: "p9_8",
      collectionid: "p9",
      question: "Я хороший",
      answer: "I am good ",
      note: "",
    },
    {
      id: "p9_9",
      collectionid: "p9",
      question: "Ты хороший",
      answer: "you are good ",
      note: "",
    },
    {
      id: "p9_10",
      collectionid: "p9",
      question: "Мы хорошие",
      answer: "We are good ",
      note: "",
    },
    {
      id: "p9_11",
      collectionid: "p9",
      question: "Вы хорошие",
      answer: "You are good ",
      note: "",
    },
    {
      id: "p9_12",
      collectionid: "p9",
      question: "Они хорошие",
      answer: "They are good ",
      note: "",
    },
    {
      id: "p9_13",
      collectionid: "p9",
      question: "Она хорошая",
      answer: "She is goods ",
      note: "",
    },
    {
      id: "p9_14",
      collectionid: "p9",
      question: "Он хороший",
      answer: "He is goods ",
      note: "",
    },
    {
      id: "p9_15",
      collectionid: "p9",
      question: "Оно хорошее",
      answer: "It is goods ",
      note: "",
    },
    {
      id: "p9_16",
      collectionid: "p9",
      question: "Я плохой",
      answer: "I am bad ",
      note: "",
    },
    {
      id: "p9_17",
      collectionid: "p9",
      question: "Ты плохой",
      answer: "you are bad ",
      note: "",
    },
    {
      id: "p9_18",
      collectionid: "p9",
      question: "Мы плохие",
      answer: "We are bad ",
      note: "",
    },
    {
      id: "p9_19",
      collectionid: "p9",
      question: "Вы плохие",
      answer: "You are bad ",
      note: "",
    },
    {
      id: "p9_20",
      collectionid: "p9",
      question: "Они плохие",
      answer: "They are bad ",
      note: "",
    },
    {
      id: "p9_21",
      collectionid: "p9",
      question: "Она плохая",
      answer: "She is bad ",
      note: "",
    },
    {
      id: "p9_22",
      collectionid: "p9",
      question: "Он плохой",
      answer: "He is bad ",
      note: "",
    },
    {
      id: "p9_23",
      collectionid: "p9",
      question: "Это плохо",
      answer: "It is bad ",
      note: "",
    },
    {
      id: "p9_24",
      collectionid: "p9",
      question: "Я на работе ",
      answer: "I am at work ",
      note: "",
    },
    {
      id: "p9_25",
      collectionid: "p9",
      question: "Ты на работе ",
      answer: "you are at work ",
      note: "",
    },
    {
      id: "p9_26",
      collectionid: "p9",
      question: "Мы на работе ",
      answer: "We are at work ",
      note: "",
    },
    {
      id: "p9_27",
      collectionid: "p9",
      question: "Вы на работе ",
      answer: "You are at work ",
      note: "",
    },
    {
      id: "p9_28",
      collectionid: "p9",
      question: "Они на работе ",
      answer: "They are at work ",
      note: "",
    },
    {
      id: "p9_29",
      collectionid: "p9",
      question: "Она на работе ",
      answer: "She is at work ",
      note: "",
    },
    {
      id: "p9_30",
      collectionid: "p9",
      question: "Он на работе ",
      answer: "He is at work ",
      note: "",
    },
    {
      id: "p9_31",
      collectionid: "p9",
      question: "Я дома ",
      answer: "I am at home ",
      note: "",
    },
    {
      id: "p9_32",
      collectionid: "p9",
      question: "Ты дома ",
      answer: "you are at home ",
      note: "",
    },
    {
      id: "p9_33",
      collectionid: "p9",
      question: "Мы дома ",
      answer: "We are at home ",
      note: "",
    },
    {
      id: "p9_34",
      collectionid: "p9",
      question: "Вы дома ",
      answer: "You are at home ",
      note: "",
    },
    {
      id: "p9_35",
      collectionid: "p9",
      question: "Они дома ",
      answer: "They are at home ",
      note: "",
    },
    {
      id: "p9_36",
      collectionid: "p9",
      question: "Она дома ",
      answer: "She is at home ",
      note: "",
    },
    {
      id: "p9_37",
      collectionid: "p9",
      question: "Он дома ",
      answer: "He is at home ",
      note: "",
    },
    {
      id: "p9_38",
      collectionid: "p9",
      question: "Оно дома ",
      answer: "It is at home ",
      note: "",
    },
    {
      id: "p9_39",
      collectionid: "p9",
      question: "Я счастливый",
      answer: "I am happy ",
      note: "",
    },
    {
      id: "p9_40",
      collectionid: "p9",
      question: "Ты счастливый",
      answer: "you are happy ",
      note: "",
    },
    {
      id: "p9_41",
      collectionid: "p9",
      question: "Мы счастливые",
      answer: "We are happy ",
      note: "",
    },
    {
      id: "p9_42",
      collectionid: "p9",
      question: "Вы счастливые",
      answer: "You are happy ",
      note: "",
    },
    {
      id: "p9_43",
      collectionid: "p9",
      question: "Они счастливые",
      answer: "They are happy ",
      note: "",
    },
    {
      id: "p9_44",
      collectionid: "p9",
      question: "Она счастливая",
      answer: "She is happy ",
      note: "",
    },
    {
      id: "p9_45",
      collectionid: "p9",
      question: "Он счастливый",
      answer: "He is happy ",
      note: "",
    },
    {
      id: "p9_46",
      collectionid: "p9",
      question: "Я злюсь",
      answer: "I am angry ",
      note: "",
    },
    {
      id: "p9_47",
      collectionid: "p9",
      question: "Ты злишься",
      answer: "you are angry ",
      note: "",
    },
    {
      id: "p9_48",
      collectionid: "p9",
      question: "Мы злимся",
      answer: "We are angry ",
      note: "",
    },
    {
      id: "p9_49",
      collectionid: "p9",
      question: "Вы злитесь",
      answer: "You are angry ",
      note: "",
    },
    {
      id: "p9_50",
      collectionid: "p9",
      question: "Они злятся",
      answer: "They are angry ",
      note: "",
    },
    {
      id: "p9_51",
      collectionid: "p9",
      question: "Она злится",
      answer: "She is angry ",
      note: "",
    },
    {
      id: "p9_52",
      collectionid: "p9",
      question: "Он злится",
      answer: "He is angry ",
      note: "",
    },
  ],
};
export default dataBase;
